services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
